#!/bin/bash
#: Title	: hw
#: Date		: 2024-02-10
#: Author	: Audience Kayela
#: Version	: 1.0
#: Description	: Print Hello and the first command-line argument 
#: Options	: None

printf "Hello, %s!\n" "$1"
